# ── API & Server ──────────────────────────────────────────────
server:
  port: ${GATEWAY_PORT}

# ── Spring Boot Core ──────────────────────────────────────────
spring:
  application:
    name: gateway-service

# ── Security ──────────────────────────────────────────────────
  security:
    oauth2:
      resourceserver:
        jwt:
          # This triggers the automatic discovery and key fetch
          issuer-uri: ${JWT_ISSUER_URI}

# ── Spring Cloud Gateway ──────────────────────────────────────
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            #  PROTECT INTERNAL ACTUATORS
            - id: block-internal-actuator
              uri: no://op
              predicates:
                - Path=/*/actuator/**
              filters:
                - SetStatus=403

            # USER SERVICE
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/profiles/**

            # JOB SERVICE
            - id: job-service
              uri: lb://job-service
              predicates:
                - Path=/api/v1/jobs/**

            # SEARCH SERVICE
            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=/api/v1/search/**

            # SEARCH SERVICE
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/v1/applications/**

# ── Service Discovery ───────────────────────────────────────────
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}

# ── Logging ─────────────────────────────────────────────────────
logging:
  level:
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY}
