services:
  # ─── Infrastructure ───────────────────────────────────────────
  discovery-service:
    build:
      context: ../infrastructure/discovery-service
    container_name: discovery-service-job-board
    ports:
      - "${DISCOVERY_PORT}:${DISCOVERY_PORT}"
    environment:
      DISCOVERY_PORT: ${DISCOVERY_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}
    networks:
      - job-board-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:${MANAGEMENT_PORT}/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  gateway-service:
    build:
      context: ../infrastructure/gateway-service
    container_name: gateway-service-job-board
    environment:
      # Server
      GATEWAY_PORT: ${GATEWAY_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Security (Resource Server)
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}

      #Logging
      LOG_LEVEL_GATEWAY: ${LOG_LEVEL_GATEWAY}

    depends_on:
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started

    networks:
      - job-board-net
    restart: unless-stopped

  # ─── Services ───────────────────────────────────────────
  auth-service:
    build:
      context: ../services/auth-service
    container_name: auth-service-job-board
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      # Server
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      #Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      DATASOURCE_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${AUTH_DB}
      DATASOURCE_USERNAME: ${PG_USER}
      DATASOURCE_PASSWORD: ${PG_PASSWORD}

      # OAuth2 / Auth Server Config
      BFF_CLIENT_ID: ${BFF_CLIENT_ID}
      BFF_CLIENT_SECRET: ${BFF_CLIENT_SECRET}
      BFF_REDIRECT_URI: ${BFF_REDIRECT_URI}
      POST_LOGOUT_REDIRECT_URI: ${POST_LOGOUT_REDIRECT_URI}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      NOTIFICATION_CLIENT_ID: ${NOTIFICATION_CLIENT_ID}
      NOTIFICATION_SERVICE_SECRET: ${NOTIFICATION_SERVICE_SECRET}

      # Token Settings
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      REQUIRE_CONSENT: ${REQUIRE_CONSENT}
      REQUIRE_PKCE: ${REQUIRE_PKCE}

      # Security Keys
      KEYSTORE_PATH: ${KEYSTORE_PATH}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      KEY_ALIAS: ${KEY_ALIAS}
      HMAC_SECRET_KEY: ${SECRET_KEY}

      #Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}

      # Logging
      LOG_LEVEL_SECURITY: ${LOG_LEVEL_SECURITY}
      LOG_LEVEL_OAUTH2: ${LOG_LEVEL_OAUTH2}

    volumes:
      # Mount the folder containing the .jks file so the app can read it
      - ../services/auth-service/src/main/resources/job-board.jks:/app/config/job-board.jks

    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:${MANAGEMENT_PORT}/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  bff-service:
    build:
      context: ../services/bff-service
    container_name: bff-service-job-board
    ports:
      - "${BFF_PORT}:${BFF_PORT}"
      - "${MANAGEMENT_PORT}:${MANAGEMENT_PORT}"
    environment:
      # Server
      BFF_PORT: ${BFF_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      #Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Redis (Session Management)
      RD_HOST: ${RD_HOST}
      RD_PORT: ${RD_PORT}
      RD_PASSWORD: ${RD_PASSWORD}

      # OAuth2 Client Config (BFF Role)
      BFF_CLIENT_ID: ${BFF_CLIENT_ID}
      BFF_CLIENT_SECRET: ${BFF_CLIENT_SECRET}
      BFF_REDIRECT_URI: ${BFF_REDIRECT_URI}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      SESSION_SECURE: ${SESSION_SECURE}

      # Routing
      GATEWAY_URL: ${GATEWAY_SERVICE_URL}
      FRONTEND_URL: ${FRONTEND_URL}

      # Logging
      LOG_LEVEL_SECURITY: ${LOG_LEVEL_SECURITY}
      LOG_LEVEL_GATEWAY: ${LOG_LEVEL_GATEWAY}

    depends_on:
      redis:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped

  user-service:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile
    container_name: user-service-job-board
    environment:
      # Server
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_SERVICE_GRPC_PORT: ${USER_SERVICE_GRPC_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      DATASOURCE_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${USER_DB}
      DATASOURCE_USERNAME: ${PG_USER}
      DATASOURCE_PASSWORD: ${PG_PASSWORD}

      # Security
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      HMAC_SECRET_KEY: ${SECRET_KEY}

      # Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}
      KF_CONSUMER_GROUP_ID: ${KF_USER_CONSUMER_GROUP_ID}

      # Cloudinary
      CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      API_KEY: ${CLOUDINARY_API_KEY}
      API_SECRET: ${CLOUDINARY_API_SECRET}

    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped

  job-service:
    build:
      context: ../services/job-service
      dockerfile: Dockerfile
    container_name: job-service-job-board
    environment:
      # Server
      JOB_SERVICE_PORT: ${JOB_SERVICE_PORT}
      JOB_SERVICE_GRPC_PORT: ${JOB_SERVICE_GRPC_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      DATASOURCE_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${JOB_DB}
      DATASOURCE_USERNAME: ${PG_USER}
      DATASOURCE_PASSWORD: ${PG_PASSWORD}

      # Security
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      HMAC_SECRET_KEY: ${SECRET_KEY}

      # Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}
      KF_CONSUMER_GROUP_ID: ${KF_JOB_CONSUMER_GROUP_ID}

    depends_on:
      postgres:
        condition: service_healthy
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped

  search-service:
    build:
      context: ../services/search-service
      dockerfile: Dockerfile
    container_name: search-service-job-board
    environment:
      # Server
      SEARCH_SERVICE_PORT: ${SEARCH_SERVICE_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      ELASTICSEARCH_URIS: http://elasticsearch:9200

      # Security
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      HMAC_SECRET_KEY: ${SECRET_KEY}

      # Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}
      KF_SEARCH_CONSUMER_GROUP_ID: ${KF_SEARCH_CONSUMER_GROUP_ID}

    depends_on:
      discovery-service:
        condition: service_started
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped

  application-service:
    build:
      context: ../services/application-service
      dockerfile: Dockerfile
    container_name: application-service-job-board
    environment:
      # Server
      APPLICATION_SERVICE_PORT: ${APPLICATION_SERVICE_PORT}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      DATASOURCE_URL: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${APPLICATION_DB}
      DATASOURCE_USERNAME: ${PG_USER}
      DATASOURCE_PASSWORD: ${PG_PASSWORD}

      # Security
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      HMAC_SECRET_KEY: ${SECRET_KEY}

      # Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}
      KF_CONSUMER_GROUP_ID: ${KF_JOB_CONSUMER_GROUP_ID}

    depends_on:
      postgres:
        condition: service_healthy
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped

  notification-service:
    build:
      context: ../services/notification-service
    container_name: notification-service-job-board
    environment:
      # Server
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}

      # Discovery
      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}

      # Database
      MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin

      # OAuth2 Client Config
      NOTIFICATION_CLIENT_ID: ${NOTIFICATION_CLIENT_ID}
      NOTIFICATION_SERVICE_SECRET: ${NOTIFICATION_SERVICE_SECRET}
      AUTH_SERVICE_TOKEN_URI: ${AUTH_SERVICE_TOKEN_URI}

      # Security
      HMAC_SECRET_KEY: ${SECRET_KEY}

      # Kafka
      KF_BOOTSTRAP_SERVERS: ${KF_BOOTSTRAP_SERVERS}
      SC_REGISTRY_URL: ${SC_REGISTRY_URL}
      KF_CONSUMER_GROUP_ID: ${KF_JOB_CONSUMER_GROUP_ID}

      # Mail
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}

      # Logging
      LOG_LEVEL_MAIL: ${LOG_LEVEL_MAIL}

    depends_on:
      mongodb:
        condition: service_healthy
      kafka-0:
        condition: service_healthy

    networks:
      - job-board-net
    restart: unless-stopped