services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin-job-board
    ports:
      - "${PGADMIN_PORT_HOST}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - job-board-net
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgadmin_data: