syntax = "proto3";

package jobboard.user.event;
option java_package = "com.echcherqaoui.jobboard.user.event";
option java_multiple_files = true;

import "google/protobuf/timestamp.proto";

message CompanyUpsertedEvent {
  string event_id = 1;
  string recruiter_id = 2;
  string company_name = 3;
  string company_logo = 4;
  string signature = 5;
  google.protobuf.Timestamp occurred_at = 6;
}

message CompanyDeletedEvent {
  string event_id = 1;
  string recruiter_id = 2;
  string signature = 3;
  google.protobuf.Timestamp occurred_at = 4;
}