syntax = "proto3";

package com.echcherqaoui.jobboard;

option java_package = "com.echcherqaoui.jobboard.event";
option java_outer_classname = "JobEventProto";
option java_multiple_files = true;

import "google/protobuf/timestamp.proto";

message JobEvent {
  string event_id = 1;
  string event_type = 2; // JOB_CREATED | JOB_UPDATED | JOB_STATUS_CHANGED | JOB_DELETED
  string job_id = 3;
  string recruiter_id = 4;
  string company_name = 5;
  string company_logo = 6;
  string title = 7;
  string description = 8;
  string requirements = 9;
  string location = 10;
  string work_modality = 11;
  string job_type = 12;
  string experience_level = 13;
  int64 salary_min_cents = 14;
  int64 salary_max_cents = 15;
  string currency = 16;
  string status = 17;
  repeated string skills = 18;
  optional google.protobuf.Timestamp expires_at = 19;
  google.protobuf.Timestamp created_at = 20;
  google.protobuf.Timestamp occurred_at = 21;
  string signature = 22;
}